version: '3.7'
services:
  server:
    # load nestjs from ./server/Dockerfile
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/usr/src/app/server
    env_file:
      - .env
  client:
    # load react from ./client/Dockerfile
    build: ./client
    ports:
      - 80:80
    volumes:
      - ./client:/usr/src/app/client
    env_file:
      - .env
    depends_on:
      - server



