version: '3.7'
services:
  server:
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/usr/src/app/server
    env_file:
      - dev.env
  client:
    build: ./client
    ports:
      - 80:80
    volumes:
      - ./client:/usr/src/app/client
    env_file:
      - dev.env
    depends_on:
      - server
