import "./globals.css";

import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Providers } from "./providers";
import Header from "./_header/Header";
const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="vi" className="">
            <head>
                <link rel="icon" href="/favicon.png" sizes="any" />
            </head>
            <body className={`${inter.className} bg-default-100 h-full `}>
                <Providers>
                    <Header />
                    <main className="container ">{children}</main>
                </Providers>
            </body>
        </html>
    );
}
