import "./globals.css";

import type { Metadata } from "next";
import { Providers } from "./providers";
import Header from "./_header/Header";
import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// -a---           1/13/2020  9:26 PM          93564 Poppins-Black.otf
// -a---           1/13/2020  9:26 PM         101016 Poppins-BlackItalic.otf
// -a---           1/13/2020  9:26 PM          95496 Poppins-Bold.otf
// -a---           1/13/2020  9:26 PM         106216 Poppins-BoldItalic.otf
// -a---           1/13/2020  9:26 PM          95312 Poppins-ExtraBold.otf
// -a---           1/13/2020  9:26 PM         106072 Poppins-ExtraBoldItalic.otf
// -a---           1/13/2020  9:26 PM          95476 Poppins-ExtraLight.otf
// -a---           1/13/2020  9:26 PM         107932 Poppins-ExtraLightItalic.otf
// -a---           1/13/2020  9:26 PM         106944 Poppins-Italic.otf
// -a---           1/13/2020  9:26 PM          95240 Poppins-Light.otf
// -a---           1/13/2020  9:26 PM         107924 Poppins-LightItalic.otf
// -a---           1/13/2020  9:26 PM          94316 Poppins-Medium.otf
// -a---           1/13/2020  9:26 PM         105848 Poppins-MediumItalic.otf
// -a---           1/13/2020  9:26 PM          95176 Poppins-Regular.otf
// -a---           1/13/2020  9:26 PM          95944 Poppins-SemiBold.otf
// -a---           1/13/2020  9:26 PM         107144 Poppins-SemiBoldItalic.otf
// -a---           1/13/2020  9:26 PM          90036 Poppins-Thin.otf
// -a---           1/13/2020  9:26 PM         101460 Poppins-ThinItalic.otf
const poppins = localFont({
    src: [
        {
            path: "../assets/font-poppins/Poppins-SemiBold.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../assets/font-poppins/Poppins-Italic.otf",
            weight: "400",
            style: "italic",
        },
        {
            path: "../assets/font-poppins/Poppins-Bold.otf",
            weight: "700",
            style: "normal",
        },
        {
            path: "../assets/font-poppins/Poppins-BoldItalic.otf",
            weight: "700",
            style: "italic",
        },
    ],
    variable: "--font-poppins",
});
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="vi">
            <head>
                <link rel="icon" href="/favicon.png" sizes="any" />
            </head>
            <body className={`${poppins.variable} font-sans bg-default-100 h-full `}>
                <Providers>
                    <NextTopLoader color="#005FCC" />
                    <Header />
                    <main className="container py-2 ">{children}</main>
                </Providers>
            </body>
        </html>
    );
}
