import "./globals.css";

import type { Metadata } from "next";
import { Providers } from "./providers";
import Header from "./_header/Header";
import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";
import AuthProvider from "./AuthProvider";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const poppins = localFont({
    src: [
        {
            path: "../assets/font-poppins/Poppins-SemiBold.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../assets/font-poppins/Poppins-Italic.otf",
            weight: "400",
            style: "italic",
        },
        {
            path: "../assets/font-poppins/Poppins-Bold.otf",
            weight: "700",
            style: "normal",
        },
        {
            path: "../assets/font-poppins/Poppins-BoldItalic.otf",
            weight: "700",
            style: "italic",
        },
    ],
    variable: "--font-poppins",
});
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="vi">
            <head>
                <link rel="icon" href="/favicon.png" sizes="any" />
            </head>
            <body className={`${poppins.variable} font-sans bg-default-100 h-full `}>
                <Providers>
                    <AuthProvider>
                        <NextTopLoader color="#005FCC" />
                        <Header />
                        <main className="container py-2 bg-default-50">{children}</main>
                    </AuthProvider>
                </Providers>
            </body>
        </html>
    );
}
