version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./sites-available:/etc/nginx/sites-available
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
